package docgen

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sample = `--! A small demo module that greets the world.

--! Builds a personalized greeting message.
fn greet name
    "Hello, " ++ name

--! The default greeting target.
target: "world"

--! Output levels we support.
enum Level: INFO, WARN, ERROR
`

func TestMarkdownForFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "demo.pipe")
	if err := os.WriteFile(path, []byte(sample), 0o644); err != nil {
		t.Fatal(err)
	}

	md, err := MarkdownForFile(path)
	if err != nil {
		t.Fatal(err)
	}

	for _, want := range []string{
		"# demo.pipe",
		"A small demo module that greets the world.",
		"### `fn greet`",
		"Builds a personalized greeting message.",
		"### `target`",
		"The default greeting target.",
		"### `enum Level`",
		"Output levels we support.",
	} {
		if !strings.Contains(md, want) {
			t.Errorf("markdown missing %q:\n%s", want, md)
		}
	}
}

func TestMarkdownForBuiltinsCoversAll(t *testing.T) {
	md := MarkdownForBuiltins()
	if !strings.Contains(md, "generated by `pipe -doc --builtins`") {
		t.Error("missing generation notice")
	}
	for _, h := range []string{"## MCP", "## Sandbox", "## AI Agents", "## Concurrency"} {
		if !strings.Contains(md, h) {
			t.Errorf("missing category heading %q", h)
		}
	}
}

func TestMarkdownForPathDir(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "a.pipe"), []byte(sample), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "b.pipe"), []byte("--! Second file.\nx: 1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "ignore.txt"), []byte("not pipe"), 0o644); err != nil {
		t.Fatal(err)
	}

	md, err := MarkdownForPath(dir)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{"# a.pipe", "# b.pipe", "Second file."} {
		if !strings.Contains(md, want) {
			t.Errorf("directory markdown missing %q", want)
		}
	}
	if strings.Contains(md, "ignore.txt") {
		t.Error("directory markdown must not include non-.pipe files")
	}
}
