// Package docgen renders Markdown documentation for Pipe source files and
// for the builtin reference, driven by `pipe -doc`.
package docgen

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/MachuraHarry/pipe/pkg/analysis"
	"github.com/MachuraHarry/pipe/pkg/lexer"
)

// MarkdownForPath documents a .pipe file or, for a directory, concatenates
// the documentation of every .pipe file found under it.
func MarkdownForPath(path string) (string, error) {
	info, err := os.Stat(path)
	if err != nil {
		return "", err
	}
	if !info.IsDir() {
		return MarkdownForFile(path)
	}

	var b strings.Builder
	err = filepath.Walk(path, func(p string, fi os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if fi.IsDir() || !strings.HasSuffix(p, ".pipe") {
			return nil
		}
		md, err := MarkdownForFile(p)
		if err != nil {
			return err
		}
		if b.Len() > 0 {
			b.WriteString("\n---\n\n")
		}
		b.WriteString(md)
		return nil
	})
	if err != nil {
		return "", err
	}
	return b.String(), nil
}

// MarkdownForFile documents a single .pipe source file.
func MarkdownForFile(path string) (string, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	a, _ := analysis.Analyze(string(src))
	return renderFile(path, string(src), a), nil
}

func renderFile(path string, source string, a *analysis.Analysis) string {
	var b strings.Builder
	title := filepath.Base(path)
	fmt.Fprintf(&b, "# %s\n\n", title)

	docs := lexer.CollectDocstrings(source)

	// A leading docstring block becomes the file description.
	if len(docs) > 0 && docs[0].Line == 1 {
		var desc []string
		expect := 1
		i := 0
		for i < len(docs) && docs[i].Line == expect {
			desc = append(desc, docs[i].Text)
			expect++
			i++
		}
		fmt.Fprintf(&b, "_%s_\n\n", strings.Join(desc, " "))
	}

	if len(a.Symbols) > 0 {
		writeSection(&b, "Functions", symbols(a, analysis.KindFunction))
		writeSection(&b, "Variables", symbols(a, analysis.KindVariable))
		writeSection(&b, "Enums", symbols(a, analysis.KindEnum))
		writeSection(&b, "Modules", symbols(a, analysis.KindModule))
	}
	return b.String()
}

func symbols(a *analysis.Analysis, kind analysis.SymbolKind) []*analysis.Symbol {
	var out []*analysis.Symbol
	for _, s := range a.Symbols {
		if s.Kind == kind {
			out = append(out, s)
		}
	}
	sort.SliceStable(out, func(i, j int) bool { return out[i].Pos.Line < out[j].Pos.Line })
	return out
}

func writeSection(b *strings.Builder, title string, syms []*analysis.Symbol) {
	if len(syms) == 0 {
		return
	}
	fmt.Fprintf(b, "## %s\n\n", title)
	for _, s := range syms {
		renderSymbol(b, s)
	}
}

func renderSymbol(b *strings.Builder, s *analysis.Symbol) {
	switch s.Kind {
	case analysis.KindFunction:
		fmt.Fprintf(b, "### `fn %s`\n\n", s.Name)
	case analysis.KindEnum:
		fmt.Fprintf(b, "### `enum %s`\n\n", s.Name)
	case analysis.KindModule:
		fmt.Fprintf(b, "### `import %s`\n\n", s.Name)
	default:
		fmt.Fprintf(b, "### `%s`\n\n", s.Name)
	}
	if s.Doc != "" {
		fmt.Fprintf(b, "%s\n\n", s.Doc)
	}
	if len(s.Usages) > 0 {
		fmt.Fprintf(b, "_Referenced %d time(s)._\n\n", len(s.Usages))
	}
}

// MarkdownForBuiltins renders the reference of all builtins grouped by
// category, generated from the analysis package's builtin documentation.
func MarkdownForBuiltins() string {
	docs := analysis.AllBuiltins()
	byCat := make(map[string][]analysis.BuiltinDoc)
	var cats []string
	for _, d := range docs {
		if _, ok := byCat[d.Category]; !ok {
			cats = append(cats, d.Category)
		}
		byCat[d.Category] = append(byCat[d.Category], d)
	}
	sort.Strings(cats)

	var b strings.Builder
	b.WriteString("# Pipe Builtin Reference\n\n")
	b.WriteString(fmt.Sprintf("_%d builtins, generated by `pipe -doc --builtins`._\n\n", len(docs)))
	for _, cat := range cats {
		fmt.Fprintf(&b, "## %s\n\n", cat)
		group := byCat[cat]
		sort.SliceStable(group, func(i, j int) bool { return group[i].Name < group[j].Name })
		for _, d := range group {
			fmt.Fprintf(&b, "### `%s`\n\n", d.Signature)
			if d.ReturnType != "" {
				fmt.Fprintf(&b, "_Returns: `%s`._\n\n", d.ReturnType)
			}
			if d.Description != "" {
				fmt.Fprintf(&b, "%s\n\n", d.Description)
			}
			if len(d.Params) > 0 {
				b.WriteString("| Parameter | Type |\n|---|---|\n")
				for _, p := range d.Params {
					fmt.Fprintf(&b, "| %s | `%s` |\n", p.Name, p.Type)
				}
				b.WriteString("\n")
			}
		}
	}
	return b.String()
}
