package compiler

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/MachuraHarry/pipe/pkg/ast"
	"github.com/MachuraHarry/pipe/pkg/object"
)

type SymbolScope int

const (
	GlobalScope SymbolScope = iota
	LocalScope
	BuiltinScope
	FreeScope
)

// CacheVersion identifies the emitted bytecode format AND symbol-allocation
// semantics for the .pipec on-disk cache (pkg/cache). It MUST be bumped on
// every compiler change that alters generated bytecode or global slot
// layout -- stale caches otherwise keep executing bytecode that no longer
// matches the VM, producing corrupted state instead of a clean recompile.
const CacheVersion = byte(6)

type Symbol struct {
	Name  string
	Scope SymbolScope
	Index int
	// FromImport marks symbols bound into an importing scope as a module's
	// export alias. Re-defining the name locally must allocate a fresh slot
	// instead of writing through to the module's own global.
	FromImport bool
}

type SymbolTable struct {
	store          map[string]Symbol
	numDefinitions int
	Outer          *SymbolTable
	FreeSymbols    []Symbol
	// moduleMode marks the isolated scope created for an imported module:
	// definitions allocate fresh GLOBAL slots (the VM has one globals array)
	// while lookups only fall through to the outer chain for BUILTINS --
	// mirroring the tree-walker, where a module evaluates in a fresh
	// environment that sees neither the importer's globals nor vice versa.
	moduleMode bool
}

// builtinIndexByName is a static, never-mutated lookup from builtin name to
// its object.Builtins index -- independent of any SymbolTable. It backstops
// module-mode Resolve() (see below) against a real bug: a bare `import
// "sqlite"` (or any module exporting a symbol that collides with a builtin
// name, e.g. sqlite's own `exec(handle, sql)`) flattens its exports directly
// into the IMPORTER's symbol table via Define(), which -- by design, so a
// user's own top-level redefinition of a builtin name works -- overwrites
// that table's store[name] entry in place, permanently losing the original
// BuiltinScope entry AT THAT TABLE. A later *aliased* import's isolated
// module scope (moduleMode) walks the importer's ancestor chain looking for
// a BuiltinScope entry to resolve its own builtin calls (e.g. docker_tools.
// pipe's own exec() calls, unrelated to sqlite) -- and since the shadowed
// entry it finds along the way is no longer BuiltinScope, the walk reports
// the builtin as undefined, even though nothing in the aliased module's own
// scope ever redefined it. Reproduced live: `import "sqlite"` (bare)
// followed by `import "modules/docker_tools.pipe" as dt` under `-vm` failed
// to compile with "undefined variable: exec"; the tree-walker (which
// evaluates builtins from a persistent, never-mutated registry instead of a
// mutable scope chain) was unaffected. This fallback is consulted only
// after the normal ancestor walk fails, so it changes nothing for the
// common case where no shadowing occurred.
var builtinIndexByName = func() map[string]int {
	m := make(map[string]int, len(object.Builtins))
	for i, b := range object.Builtins {
		m[b.Name] = i
	}
	return m
}()

func NewSymbolTable() *SymbolTable {
	return &SymbolTable{store: make(map[string]Symbol)}
}

func NewEnclosedSymbolTable(outer *SymbolTable) *SymbolTable {
	s := NewSymbolTable()
	s.Outer = outer
	return s
}

// NewModuleSymbolTable returns the isolated symbol scope used while
// compiling an imported module.
func NewModuleSymbolTable(outer *SymbolTable) *SymbolTable {
	s := NewSymbolTable()
	s.Outer = outer
	s.moduleMode = true
	return s
}

func (s *SymbolTable) root() *SymbolTable {
	t := s
	for t.Outer != nil {
		t = t.Outer
	}
	return t
}

func (s *SymbolTable) Define(name string) Symbol {
	if existing, ok := s.store[name]; ok && !existing.FromImport {
		if s.Outer != nil || existing.Scope != BuiltinScope {
			return existing
		}
		// A global definition shadows a builtin of the same name: the VM
		// must mirror the tree-walker, where a program or module definition
		// (`env.Set`) takes precedence over the builtin. Rebind the slot as a
		// fresh global with a real global index (builtins live in a separate
		// index space and never bump numDefinitions).
	}
	sym := Symbol{Name: name}
	if s.moduleMode {
		// Module bindings live in their own scope but occupy real global
		// slots, allocated from the root counter shared by all scopes.
		r := s.root()
		sym.Index = r.numDefinitions
		r.numDefinitions++
		sym.Scope = GlobalScope
	} else {
		sym.Index = s.numDefinitions
		if s.Outer == nil {
			sym.Scope = GlobalScope
		} else {
			sym.Scope = LocalScope
		}
		s.numDefinitions++
	}
	s.store[name] = sym
	return sym
}

// DefineAlias binds name in this scope as an alias for an imported module's
// exported symbol. The symbol keeps its module-side global index; no new slot
// is allocated. A later local Define of the same name replaces the binding
// with a fresh slot (see Symbol.FromImport).
func (s *SymbolTable) DefineAlias(name string, target Symbol) {
	target.Name = name
	target.FromImport = true
	s.store[name] = target
}

func (s *SymbolTable) Resolve(name string) (Symbol, bool) {
	if s.moduleMode {
		if sym, ok := s.store[name]; ok {
			return sym, true
		}
		// Modules see builtins but not the importer's globals. Walk the full
		// ancestor chain and accept only BuiltinScope bindings: a global of
		// the same name in an importer must neither mask the builtin nor end
		// the walk short of the root, where builtins live.
		for t := s.Outer; t != nil; t = t.Outer {
			if sym, ok := t.store[name]; ok && sym.Scope == BuiltinScope {
				return sym, true
			}
		}
		// The ancestor walk above found either nothing, or a same-named entry
		// that an importer's own code (e.g. a bare `import "sqlite"`
		// flattening its exported `exec`) shadowed a builtin with -- in
		// either case, fall back to the static builtin registry so this
		// module's OWN builtin calls still resolve, unaffected by whatever
		// an unrelated ancestor scope happened to redefine (see
		// builtinIndexByName).
		if idx, ok := builtinIndexByName[name]; ok {
			return Symbol{Name: name, Scope: BuiltinScope, Index: idx}, true
		}
		return Symbol{}, false
	}
	sym, ok := s.store[name]
	if !ok && s.Outer != nil {
		outerSym, outerOk := s.Outer.Resolve(name)
		if !outerOk {
			return Symbol{}, false
		}
		if outerSym.Scope == GlobalScope || outerSym.Scope == BuiltinScope {
			return outerSym, true
		}
		free := Symbol{Name: name, Scope: FreeScope, Index: len(s.FreeSymbols)}
		s.store[name] = free
		s.FreeSymbols = append(s.FreeSymbols, outerSym)
		return free, true
	}
	return sym, ok
}

// ResolveInCurrent returns the symbol bound in the current scope only, without
// walking the outer chain. Used for assignments (VarStatement): a value being
// bound must shadow any outer global or captured local, matching the
// tree-walker, which writes into the current environment.
func (s *SymbolTable) ResolveInCurrent(name string) (Symbol, bool) {
	sym, ok := s.store[name]
	return sym, ok
}

func (s *SymbolTable) DefineBuiltin(index int, name string) Symbol {
	sym := Symbol{Name: name, Index: index, Scope: BuiltinScope}
	s.store[name] = sym
	return sym
}

type Compiler struct {
	constants   []object.Object
	symbolTable *SymbolTable
	scopes      []CompilationScope
	scopeIndex  int
	loopStack   []LoopContext
	// forInCounter generates unique internal bookkeeping-symbol names for
	// each `for x in y` loop compiled (see compileForIn) -- MUST be unique
	// per loop, not per scope: a nested for-loop compiles in the SAME
	// symbol-table scope as its enclosing loop (for-loops don't open their
	// own enclosed scope), so two hardcoded names would collide.
	forInCounter int
	importCache map[string]*ast.Program
	// importedExports caches the export bindings of modules already compiled
	// via unaliased import, so a second `import "m"` re-injects the aliases
	// without recompiling the module (matching the tree-walker's shared
	// module instance).
	importedExports map[string][]Symbol
	importStack     []string
	sourceFile      string
	currentLine     int

	// setupAbortProbes collects OpTestAbortIfError probe positions emitted by
	// `test setup` / `test teardown` hooks. They are patched to the end of the
	// compiled program: an error in a hook makes the VM exit with that error
	// (a failing setup skips the tests, matching the tree-walker's abort).
	setupAbortProbes []int
}

type LoopContext struct {
	continueTarget  int   // position to jump to on continue (condition check)
	continuePatches []int // positions of continue jumps to patch (C-style for)
	breakPatches    []int // positions of break jump instructions to patch
}

type CompilationScope struct {
	instructions  Instructions
	lines         []int // source line per emitted byte (parallel to instructions)
	deferred      []Instructions
	deferredLines [][]int
}

type CompiledScope struct {
	Instructions Instructions
	Lines        []int
	NumLocals    int
	FreeSymbols  []Symbol
}

type Bytecode struct {
	Instructions Instructions
	Lines        []int // source line per instruction byte
	Constants    []object.Object
	SourceFile   string // originating .pipe file, for positioned error messages
}

func New() *Compiler {
	return NewWithFile("")
}

func NewWithFile(sourceFile string) *Compiler {
	mainScope := CompilationScope{
		instructions: Instructions{},
	}

	symbolTable := NewSymbolTable()
	for i, b := range object.Builtins {
		symbolTable.DefineBuiltin(i, b.Name)
	}

	return &Compiler{
		constants:       []object.Object{},
		symbolTable:     symbolTable,
		scopes:          []CompilationScope{mainScope},
		scopeIndex:      0,
		importCache:     make(map[string]*ast.Program),
		importedExports: make(map[string][]Symbol),
		sourceFile:      sourceFile,
	}
}

func (c *Compiler) currentScope() *CompilationScope {
	return &c.scopes[c.scopeIndex]
}

func (c *Compiler) currentInstructions() Instructions {
	return c.currentScope().instructions
}

func (c *Compiler) Bytecode() *Bytecode {
	scope := c.currentScope()
	// Emit top-level deferred expressions before returning bytecode
	for i := len(scope.deferred) - 1; i >= 0; i-- {
		scope.instructions = append(scope.instructions, scope.deferred[i]...)
		scope.lines = append(scope.lines, scope.deferredLines[i]...)
	}
	scope.deferred = nil
	scope.deferredLines = nil

	bc := &Bytecode{
		Instructions: scope.instructions,
		Lines:        scope.lines,
		Constants:    c.constants,
		SourceFile:   c.sourceFile,
	}

	// Jump optimization disabled: fragile with try/catch/join patterns.
	// Re-enable once all compilation patterns are audited.
	return bc
}

func (c *Compiler) emit(op Opcode, operands ...int) int {
	ins := Make(op, operands...)
	scope := c.currentScope()
	pos := len(scope.instructions)
	scope.instructions = append(scope.instructions, ins...)
	for range ins {
		scope.lines = append(scope.lines, c.currentLine)
	}
	return pos
}

func (c *Compiler) emitUint16(v uint16) {
	ins := encodeUint16(v)
	scope := c.currentScope()
	scope.instructions = append(scope.instructions, ins...)
	for range ins {
		scope.lines = append(scope.lines, c.currentLine)
	}
}

func (c *Compiler) addConstant(obj object.Object) int {
	c.constants = append(c.constants, obj)
	return len(c.constants) - 1
}

func (c *Compiler) addString(s string) int {
	return c.addConstant(&object.String{Value: s})
}

func (c *Compiler) addInteger(v int64) int {
	return c.addConstant(&object.Integer{Value: v})
}

func (c *Compiler) addFloat(v float64) int {
	return c.addConstant(&object.Float{Value: v})
}

func (c *Compiler) Compile(node ast.Node) error {
	if pn, ok := node.(interface{ Pos() ast.Position }); ok {
		if pos := pn.Pos(); pos.Line > 0 {
			c.currentLine = pos.Line
		}
	}
	switch n := node.(type) {
	case *ast.Program:
		// Two-pass: compile definitions first, then expressions
		c.defineTopLevelSymbols(n.Statements)
		return c.compileProgram(n.Statements)

	case *ast.BlockStatement:
		return c.compileStatements(n.Statements, true)

	case *ast.ExpressionStatement:
		if err := c.Compile(n.Expression); err != nil {
			return err
		}
		c.emit(OpPop)

	case *ast.VarStatement:
		return c.compileVarStatement(n, false)

	case *ast.IntegerLiteral:
		idx := c.addInteger(n.Value)
		c.emit(OpConstant, idx)

	case *ast.FloatLiteral:
		idx := c.addFloat(n.Value)
		c.emit(OpConstant, idx)

	case *ast.StringLiteral:
		idx := c.addString(n.Value)
		c.emit(OpConstant, idx)

	case *ast.BooleanLiteral:
		if n.Value {
			c.emit(OpTrue)
		} else {
			c.emit(OpFalse)
		}

	case *ast.NilLiteral:
		c.emit(OpNil)

	case *ast.Identifier:
		symbol, ok := c.symbolTable.Resolve(n.Value)
		if !ok {
			return fmt.Errorf("undefined variable: %s", n.Value)
		}
		c.loadSymbol(symbol)
		if symbol.Scope == BuiltinScope && isZeroArityBuiltin(n.Value) {
			c.emit(OpCall, 0)
		}

	case *ast.PrefixExpression:
		if folded, ok := c.foldExpression(n); ok {
			c.emitConstant(folded)
			return nil
		}
		if err := c.Compile(n.Right); err != nil {
			return err
		}
		if n.Operator == "-" {
			c.emit(OpMinus)
		} else if n.Operator == "!" {
			c.emit(OpNot)
		} else {
			return fmt.Errorf("unknown prefix: %s", n.Operator)
		}

	case *ast.InfixExpression:
		if folded, ok := c.foldExpression(n); ok {
			c.emitConstant(folded)
			return nil
		}
		if n.Operator == "&&" {
			if err := c.Compile(n.Left); err != nil {
				return err
			}
			c.emit(OpDup)
			jumpFalsy := c.emit(OpJumpNotTruthy, 9999)
			c.emit(OpPop)
			if err := c.Compile(n.Right); err != nil {
				return err
			}
			afterRight := len(c.currentInstructions())
			c.patchJump(jumpFalsy, afterRight)
			return nil
		}
		if n.Operator == "||" {
			if err := c.Compile(n.Left); err != nil {
				return err
			}
			c.emit(OpDup)
			jumpEnd := c.emit(OpJumpNotTruthy, 9999) // if falsy, skip to eval right
			jumpEnd2 := c.emit(OpJump, 9999)         // if truthy, skip right entirely
			c.patchJump(jumpEnd, len(c.currentInstructions()))
			c.emit(OpPop)
			if err := c.Compile(n.Right); err != nil {
				return err
			}
			c.patchJump(jumpEnd2, len(c.currentInstructions()))
			return nil
		}
		if n.Operator == "[]" {
			// Index access lowers to a call of the `at` builtin. It MUST be
			// handled before the generic Left/Right pre-compilation below,
			// otherwise the operands are emitted twice (stack imbalance under
			// the VM and duplicated side effects).
			symbol := c.resolveBuiltin("at")
			if symbol.Scope != BuiltinScope {
				return fmt.Errorf("builtin not found: at")
			}
			c.emit(OpGetBuiltin, symbol.Index)
			if err := c.Compile(n.Left); err != nil {
				return err
			}
			if err := c.Compile(n.Right); err != nil {
				return err
			}
			c.emit(OpCall, 2)
			return nil
		}
		if err := c.Compile(n.Left); err != nil {
			return err
		}
		if err := c.Compile(n.Right); err != nil {
			return err
		}
		switch n.Operator {
		case "+":
			c.emit(OpAdd)
		case "-":
			c.emit(OpSub)
		case "*":
			c.emit(OpMul)
		case "/":
			c.emit(OpDiv)
		case "%":
			c.emit(OpMod)
		case "**":
			c.emit(OpPow)
		case "==":
			c.emit(OpEqual)
		case "!=":
			c.emit(OpNotEqual)
		case ">":
			c.emit(OpGreater)
		case "<":
			c.emit(OpLess)
		case ">=":
			c.emit(OpGte)
		case "<=":
			c.emit(OpLte)
		case "++":
			c.emit(OpConcat)
		default:
			return fmt.Errorf("unknown operator: %s", n.Operator)
		}

	case *ast.IfExpression:
		if err := c.Compile(n.Condition); err != nil {
			return err
		}
		jumpNotTruthyPos := c.emit(OpJumpNotTruthy, 9999)
		if err := c.compileBlockLastReturn(n.Consequence); err != nil {
			return err
		}

		if n.Alternative != nil {
			jumpPos := c.emit(OpJump, 9999)
			afterConsequence := len(c.currentInstructions())
			c.patchJump(jumpNotTruthyPos, afterConsequence)
			if err := c.compileBlockLastReturn(n.Alternative); err != nil {
				return err
			}
			afterAlternative := len(c.currentInstructions())
			c.patchJump(jumpPos, afterAlternative)
		} else {
			jumpPos := c.emit(OpJump, 9999)
			falseBranch := len(c.currentInstructions())
			c.patchJump(jumpNotTruthyPos, falseBranch)
			c.emit(OpNil)
			afterIf := len(c.currentInstructions())
			c.patchJump(jumpPos, afterIf)
		}

	case *ast.WhileExpression:
		conditionPos := len(c.currentInstructions())
		if err := c.Compile(n.Condition); err != nil {
			return err
		}
		jumpFalsePos := c.emit(OpJumpNotTruthy, 9999)
		c.enterLoop(conditionPos)
		// Loop bodies discard their value each iteration (matching the
		// tree-walk); popLast=true prevents per-iteration stack growth.
		if err := c.compileStatements(n.Body.Statements, true); err != nil {
			return err
		}
		c.emit(OpJumpBackward, conditionPos)
		afterLoop := len(c.currentInstructions())
		c.patchJump(jumpFalsePos, afterLoop)
		c.patchBreaks(afterLoop)
		c.leaveLoop()
		c.emit(OpNil)

	case *ast.ForExpression:
		if n.IsForIn {
			return c.compileForIn(n)
		}
		return c.compileCStyleFor(n)

	case *ast.BreakStatement:
		c.addBreak()

	case *ast.ContinueStatement:
		c.emitContinue()

	case *ast.ReturnStatement:
		if n.Value != nil {
			if err := c.Compile(n.Value); err != nil {
				return err
			}
		}
		c.emit(OpReturnValue)

	case *ast.MatchExpression:
		if err := c.compileMatch(n); err != nil {
			return err
		}

	case *ast.SelectExpression:
		if err := c.compileSelect(n); err != nil {
			return err
		}

	case *ast.FnStatement:
		fnSymbol := c.symbolTable.Define(n.Name.Value)

		c.enterScope()
		for _, p := range n.Parameters {
			c.symbolTable.Define(p.Value)
		}

		if err := c.compileFnBody(n.Body); err != nil {
			return err
		}

		compiledFn := c.leaveScope()

		idx := c.addConstant(&object.CompiledFunction{
			Instructions: compiledFn.Instructions,
			Lines:        compiledFn.Lines,
			NumLocals:    compiledFn.NumLocals,
			NumFree:      len(compiledFn.FreeSymbols),
		})

		for _, freeSym := range compiledFn.FreeSymbols {
			c.loadSymbol(freeSym)
		}

		c.emit(OpClosure, idx, len(compiledFn.FreeSymbols))

		if fnSymbol.Scope == GlobalScope {
			c.emit(OpSetGlobal, fnSymbol.Index)
		} else {
			c.emit(OpSetLocal, fnSymbol.Index)
		}

	case *ast.FnLiteral:
		c.enterScope()
		for _, p := range n.Parameters {
			c.symbolTable.Define(p.Value)
		}

		if err := c.compileFnBody(n.Body); err != nil {
			return err
		}

		compiledFn := c.leaveScope()

		idx := c.addConstant(&object.CompiledFunction{
			Instructions: compiledFn.Instructions,
			Lines:        compiledFn.Lines,
			NumLocals:    compiledFn.NumLocals,
			NumFree:      len(compiledFn.FreeSymbols),
		})

		for _, freeSym := range compiledFn.FreeSymbols {
			c.loadSymbol(freeSym)
		}

		c.emit(OpClosure, idx, len(compiledFn.FreeSymbols))

	case *ast.SliceExpression:
		c.emit(OpGetBuiltin, c.resolveBuiltin("slice").Index)
		if err := c.Compile(n.List); err != nil {
			return err
		}
		if n.Start != nil {
			if err := c.Compile(n.Start); err != nil {
				return err
			}
		} else {
			c.emit(OpConstant, c.addInteger(0))
		}
		if n.End != nil {
			if err := c.Compile(n.End); err != nil {
				return err
			}
		} else {
			c.emit(OpGetBuiltin, c.resolveBuiltin("len").Index)
			if err := c.Compile(n.List); err != nil {
				return err
			}
			c.emit(OpCall, 1)
		}
		c.emit(OpCall, 3)

	case *ast.CallExpression:
		if ident, ok := n.Function.(*ast.Identifier); ok && len(n.Arguments) > 0 && isZeroArityBuiltin(ident.Value) {
			if symbol, ok := c.symbolTable.Resolve(ident.Value); ok && symbol.Scope == BuiltinScope {
				c.loadSymbol(symbol)
			} else if err := c.Compile(n.Function); err != nil {
				return err
			}
		} else if err := c.Compile(n.Function); err != nil {
			return err
		}
		for _, arg := range n.Arguments {
			if err := c.Compile(arg); err != nil {
				return err
			}
		}
		c.emit(OpCall, len(n.Arguments))

	case *ast.PipelineExpression:
		if err := c.compilePipeline(n); err != nil {
			return err
		}

	case *ast.ListLiteral:
		for _, elem := range n.Elements {
			if err := c.Compile(elem); err != nil {
				return err
			}
		}
		c.emit(OpList, len(n.Elements))

	case *ast.MapLiteral:
		keys := make([]string, 0, len(n.Pairs))
		for _, p := range n.Pairs {
			keys = append(keys, p.Key)
		}
		for _, p := range n.Pairs {
			if err := c.Compile(p.Value); err != nil {
				return err
			}
		}
		c.emit(OpMap, len(n.Pairs))
		for _, p := range n.Pairs {
			ki := c.addString(p.Key)
			c.emitUint16(uint16(ki))
		}

	case *ast.DotExpression:
		if err := c.Compile(n.Left); err != nil {
			return err
		}
		idx := c.addString(n.Field)
		c.emit(OpDot, idx)

	case *ast.TryExpression:
		if err := c.compileTryExpression(n); err != nil {
			return err
		}

	case *ast.EnumStatement:
		for i, name := range n.Values {
			sym := c.symbolTable.Define(name)
			c.emit(OpConstant, c.addInteger(int64(i)))
			if sym.Scope == GlobalScope {
				c.emit(OpSetGlobal, sym.Index)
			} else {
				c.emit(OpSetLocal, sym.Index)
			}
		}

	case *ast.StructStatement:
		def := &object.StructDef{
			Name:     n.Name,
			Fields:   make([]string, 0, len(n.Fields)),
			Defaults: make(map[string]object.Object),
		}
		for _, f := range n.Fields {
			def.Fields = append(def.Fields, f.Name)
			if f.Default != nil {
				def.Defaults[f.Name] = &object.NilObject{}
			}
		}
		sym := c.symbolTable.Define(n.Name)
		c.emit(OpConstant, c.addConstant(def))
		if sym.Scope == GlobalScope {
			c.emit(OpSetGlobal, sym.Index)
		} else {
			c.emit(OpSetLocal, sym.Index)
		}

	case *ast.ImportStatement:
		if err := c.compileImport(n); err != nil {
			return err
		}

	case *ast.ExportStatement:
		if n.Fn != nil {
			if err := c.Compile(n.Fn); err != nil {
				return err
			}
		}
		if n.Var != nil {
			if err := c.Compile(n.Var); err != nil {
				return err
			}
		}
		if n.Enum != nil {
			if err := c.Compile(n.Enum); err != nil {
				return err
			}
		}

	case *ast.DeferStatement:
		if err := c.compileDefer(n); err != nil {
			return err
		}

	case *ast.TestStatement:
		return c.compileTestStatement(n)
	}

	return nil
}

func (c *Compiler) compileProgram(stmts []ast.Statement) error {
	// Probes recorded while compiling statements of this program (including
	// code inlined from imports during pass 1). Patched below once the whole
	// program is laid out.
	probeBase := len(c.setupAbortProbes)

	// Pass 1: compile only declarations (closures, enums, exports, imports)
	// VarStatements are NOT compiled here — their values may have side effects
	// that depend on execution order (e.g., ai_provider before ai_batch).
	for _, stmt := range stmts {
		switch stmt.(type) {
		case *ast.FnStatement, *ast.EnumStatement, *ast.StructStatement,
			*ast.ExportStatement, *ast.ImportStatement:
			if err := c.Compile(stmt); err != nil {
				return err
			}
		}
	}

	// Pass 2: compile values (VarStatements) and expressions in source order
	for _, stmt := range stmts {
		switch stmt.(type) {
		case *ast.FnStatement, *ast.EnumStatement, *ast.StructStatement,
			*ast.ExportStatement, *ast.ImportStatement:
			continue
		}
		if err := c.Compile(stmt); err != nil {
			return err
		}
	}

	// An error inside a setup/teardown hook jumps past the last instruction;
	// the VM then exits with the pending error (failing the file).
	end := len(c.currentInstructions())
	for _, pos := range c.setupAbortProbes[probeBase:] {
		c.patchJump(pos, end)
	}
	return nil
}

func (c *Compiler) compileStatements(stmts []ast.Statement, popLast bool) error {
	for i, stmt := range stmts {
		if i == len(stmts)-1 && !popLast {
			switch s := stmt.(type) {
			case *ast.ExpressionStatement:
				return c.Compile(s.Expression)
			case *ast.VarStatement:
				return c.compileVarStatement(s, true)
			}
		}
		if err := c.Compile(stmt); err != nil {
			return err
		}
		// Dead code elimination: skip statements after return/break/continue
		if c.lastInstructionIsTerminator() {
			break
		}
	}
	return nil
}

func (c *Compiler) lastInstructionIsTerminator() bool {
	last, ok := lastOpcode(c.currentInstructions())
	if !ok {
		return false
	}
	return last == OpReturn || last == OpReturnValue || last == OpHalt
}

func lastOpcode(ins Instructions) (Opcode, bool) {
	if len(ins) == 0 {
		return 0, false
	}
	var last Opcode
	for i := 0; i < len(ins); {
		last = Opcode(ins[i])
		width := instructionWidthAt(ins, i, last)
		if width <= 0 || i+width > len(ins) {
			return last, true
		}
		i += width
	}
	return last, true
}

func instructionWidthAt(ins Instructions, pos int, op Opcode) int {
	switch op {
	case OpClosure:
		return 5
	case OpConstant, OpGetGlobal, OpSetGlobal, OpGetLocal, OpSetLocal,
		OpGetBuiltin, OpDot, OpGetFree,
		OpTestAbortIfError, OpTestResult, OpSelect,
		OpCall, OpSpawn, OpList,
		OpJump, OpJumpNotTruthy, OpJumpBackward:
		return 3
	case OpMap:
		if pos+3 > len(ins) {
			return len(ins) - pos
		}
		return 3 + int(ReadUint16(ins, pos+1))*2
	default:
		return 1
	}
}

// compileTestStatement compiles a `test` block so the bytecode VM matches the
// tree-walker: each statement is followed by an OpTestAbortIfError probe that
// jumps to the verdict as soon as the body produced an error (the tree-walker
// aborts a block at the first error). The verdict (OpTestResult) reports the
// test as PASS/FAIL and records failures so the runner fails the file.
func (c *Compiler) compileTestStatement(ts *ast.TestStatement) error {
	// Setup/teardown hooks are silent blocks. A probe after every statement
	// mirrors the tree-walker's block short-circuit; an error jumps past the
	// end of the program, where the VM exits with the pending error (compileProgram
	// patches these probes).
	if ts.Hook != "" {
		for _, stmt := range ts.Body.Statements {
			if err := c.Compile(stmt); err != nil {
				return err
			}
			c.setupAbortProbes = append(c.setupAbortProbes, c.emit(OpTestAbortIfError, 0))
		}
		return nil
	}

	name := ""
	if ts.Name != nil {
		name = ts.Name.Value
	}

	body := ts.Body.Statements
	var probes []int
	for i, stmt := range body {
		if i == len(body)-1 {
			switch s := stmt.(type) {
			case *ast.ExpressionStatement:
				if err := c.Compile(s.Expression); err != nil {
					return err
				}
			case *ast.VarStatement:
				if err := c.compileVarStatement(s, true); err != nil {
					return err
				}
			default:
				if err := c.Compile(stmt); err != nil {
					return err
				}
			}
			break
		}
		if err := c.Compile(stmt); err != nil {
			return err
		}
		probes = append(probes, c.emit(OpTestAbortIfError, 0))
	}

	if len(body) == 0 {
		c.emit(OpNil)
	}

	verdict := c.emit(OpTestResult, c.addConstant(&object.String{Value: name}))
	for _, pos := range probes {
		c.patchJump(pos, verdict)
	}
	return nil
}

func (c *Compiler) compileVarStatement(vs *ast.VarStatement, keepValue bool) error {
	symbol, exists := c.symbolTable.ResolveInCurrent(vs.Name.Value)
	if !exists || symbol.FromImport {
		// A fresh binding must not write through an imported alias: the
		// tree-walker's env.Set creates a new entry in the importer's
		// environment and leaves the module's own binding untouched.
		symbol = c.symbolTable.Define(vs.Name.Value)
	}
	if err := c.Compile(vs.Value); err != nil {
		return err
	}
	if keepValue {
		// Match the tree-walk: a VarStatement in value position leaves its
		// value on the stack (e.g. `x: expr` as the last statement of an
		// if-branch or function body). OpDup keeps a copy while OpSetLocal
		// consumes the original, preserving stack balance.
		c.emit(OpDup)
	}
	if symbol.Scope == GlobalScope {
		c.emit(OpSetGlobal, symbol.Index)
	} else {
		c.emit(OpSetLocal, symbol.Index)
	}
	return nil
}

func (c *Compiler) compileBlockLastReturn(block *ast.BlockStatement) error {
	return c.compileStatements(block.Statements, false)
}

func (c *Compiler) compileFnBody(body *ast.BlockStatement) error {
	if err := c.compileBlockLastReturn(body); err != nil {
		return err
	}
	if !c.lastIsReturn() {
		c.emit(OpReturnValue)
	}
	return nil
}

func (c *Compiler) compileMatch(me *ast.MatchExpression) error {
	if err := c.Compile(me.Value); err != nil {
		return err
	}

	if len(me.Cases) == 0 {
		c.emit(OpPop)
		c.emit(OpNil)
		return nil
	}

	jumpsToEnd := []int{}

	for _, cs := range me.Cases {
		wildcard := isWildcardPattern(cs.Pattern)

		// An unguarded wildcard is the terminal catch-all: it always matches,
		// so any later case is unreachable.
		if wildcard && cs.Guard == nil {
			c.emit(OpPop) // pop match value
			if err := c.Compile(cs.Body); err != nil {
				return err
			}
			jumpsToEnd = append(jumpsToEnd, c.emit(OpJump, 9999))
			break
		}

		// The match value must stay on the stack until a case actually fires,
		// so a failed pattern or guard can fall through to the next case.
		var skipNext []int
		if !wildcard {
			c.emit(OpDup)
			if err := c.Compile(cs.Pattern); err != nil {
				return err
			}
			c.emit(OpEqual)
			skipNext = append(skipNext, c.emit(OpJumpNotTruthy, 9999))
		}

		if cs.Guard != nil {
			if err := c.Compile(cs.Guard); err != nil {
				return err
			}
			c.emit(OpCheckError)
			guardOK := c.emit(OpJumpNotTruthy, 9999)
			c.emit(OpPop) // pop the error value, keep the match value on the stack
			skipNext = append(skipNext, c.emit(OpJump, 9999))
			c.patchJump(guardOK, len(c.currentInstructions()))
			skipNext = append(skipNext, c.emit(OpJumpNotTruthy, 9999))
		}

		c.emit(OpPop) // pop the matched value

		if err := c.Compile(cs.Body); err != nil {
			return err
		}
		jumpsToEnd = append(jumpsToEnd, c.emit(OpJump, 9999))

		afterCase := len(c.currentInstructions())
		for _, jmp := range skipNext {
			c.patchJump(jmp, afterCase)
		}
	}

	// Default: pop match value, push nil
	c.emit(OpPop)
	c.emit(OpNil)

	afterMatch := len(c.currentInstructions())
	for _, jmp := range jumpsToEnd {
		c.patchJump(jmp, afterMatch)
	}

	return nil
}

func isWildcardPattern(expr ast.Expression) bool {
	if ident, ok := expr.(*ast.Identifier); ok {
		return ident.Value == "_"
	}
	return false
}

func (c *Compiler) compileSelect(se *ast.SelectExpression) error {
	if len(se.Cases) == 0 {
		c.emit(OpNil)
		return nil
	}

	// For now, compile select as a simple sequential check:
	// Try each case in order, emit OpSelect with the compiled channels
	// The VM will handle the actual Go select under the hood
	for _, sc := range se.Cases {
		if sc.IsDefault {
			continue
		}
		if sc.Channel != nil {
			if err := c.Compile(sc.Channel); err != nil {
				return err
			}
		}
	}

	// Emit OpSelect with number of cases
	c.emit(OpSelect, len(se.Cases))

	// Compile each case body
	for _, sc := range se.Cases {
		if err := c.Compile(sc.Body); err != nil {
			return err
		}
		c.emit(OpPop) // pop result
	}

	return nil
}

func (c *Compiler) compileTryExpression(te *ast.TryExpression) error {
	var catchSym Symbol
	hasCatch := false
	if te.CatchParam != nil {
		catchSym = c.symbolTable.Define(te.CatchParam.Value)
		hasCatch = true
	}

	stmts := te.TryBlock.Statements

	// Compile each try statement, keeping its result on the stack so we can
	// detect errors. The tree-walker aborts a try block at the first error;
	// mirror that here by jumping to the catch binding after each statement.
	var catchJumps []int
	for i, stmt := range stmts {
		if err := c.compileTryBlockStatement(stmt); err != nil {
			return err
		}
		if i < len(stmts)-1 {
			c.emit(OpCheckError)
			okPos := c.emit(OpJumpNotTruthy, 9999)
			catchJumps = append(catchJumps, c.emit(OpJump, 9999))
			afterCheck := len(c.currentInstructions())
			c.patchJump(okPos, afterCheck)
			// OpCheckError peeks (not pops) the statement's result to check
			// it for an error, then pushes a bool on top -- so on the "no
			// error, continue to the next statement" path the statement's
			// own result value is still sitting on the stack, one below
			// where the (already-consumed-by-OpJumpNotTruthy) bool was. It's
			// never read again (only the LAST try-block statement's value
			// matters, checked by the OpCheckError right after this loop),
			// so it must be discarded here -- omitting this leaked one
			// operand-stack slot per non-final try-block statement executed
			// EVERY time that try/catch ran without erroring. Invisible for
			// a one-off try/catch, but fatal for one inside a loop: a
			// `while true` background loop (e.g. Muninn's own main poll
			// loop) running a multi-statement try block accumulates one
			// leaked slot per iteration until the operand stack overflows
			// or, further downstream, vm.frameIndex's call-depth check trips
			// first depending on what else is running. Reproduced live:
			//     i: 0
			//     while i < 2000
			//         try
			//             a: 1
			//             b: 2
			//             c: a + b
			//         catch e
			//             print "err"
			//         i: i + 1
			// crashed with "stack overflow: recursion too deep (operand
			// stack exhausted)" well before reaching i=2000; the tree-walker
			// runs this fine indefinitely.
			c.emit(OpPop)
		}
	}

	c.emit(OpCheckError)

	skipFixPos := 0
	if te.AIFix {
		skipFixPos = c.emit(OpJumpNotTruthy, 9999)
		c.emit(OpPop)
		src := blockSourceFromStatements(stmts)
		c.emit(OpConstant, c.addConstant(&object.String{Value: src}))
		c.emit(OpTryAIFix)
		c.emit(OpCheckError)
	}

	skipCatchPos := c.emit(OpJumpNotTruthy, 9999)

	// Bind the catch parameter to the error message string, matching the
	// tree-walker (catch err -> err is a string, not an Error object).
	// Bare `catch` (no parameter) simply discards the error value.
	catchBind := len(c.currentInstructions())
	if hasCatch {
		c.emit(OpErrorToString)

		// OpSetGlobal/OpSetLocal already pop the value they store (see their
		// VM implementations) -- an extra OpPop here (as the bare-`catch`
		// branch below correctly still needs, since nothing else consumes
		// its value) would over-pop by one. For OpSetGlobal that extra pop
		// only ate into unused top-level stack space (globals live in a
		// separate array, so it was harmless there) -- but for OpSetLocal it
		// dropped the VM's stack pointer one slot INTO the function's
		// reserved locals region (the catch parameter's own, highest-
		// indexed slot), so the very next value pushed while compiling the
		// catch body (e.g. the `print`/`to_str` builtin reference for a call
		// immediately using the caught error) silently overwrote it. Live
		// symptom: `catch e ... print (to_str e)` inside a function printed
		// "builtin: print" instead of the actual error message -- e's own
		// slot held whatever builtin got pushed right after it, not the
		// error string OpSetLocal had just written. Top-level (global) catch
		// was unaffected, which is what pointed at OpSetLocal specifically
		// rather than at OpErrorToString or the try/OpCheckError machinery.
		if catchSym.Scope == GlobalScope {
			c.emit(OpSetGlobal, catchSym.Index)
		} else {
			c.emit(OpSetLocal, catchSym.Index)
		}
	} else {
		c.emit(OpPop)
	}

	for _, stmt := range te.CatchBlock.Statements[:len(te.CatchBlock.Statements)-1] {
		if err := c.Compile(stmt); err != nil {
			return err
		}
	}
	if len(te.CatchBlock.Statements) > 0 {
		last := te.CatchBlock.Statements[len(te.CatchBlock.Statements)-1]
		switch s := last.(type) {
		case *ast.ExpressionStatement:
			if err := c.Compile(s.Expression); err != nil {
				return err
			}
		case *ast.VarStatement:
			// Same fix as compileTryBlockStatement's *ast.VarStatement case:
			// compileVarStatement(vs, false) (the generic *ast.VarStatement
			// path in Compile()) is already stack-neutral -- it pushes the
			// assigned value and then OpSetLocal/OpSetGlobal immediately pops
			// it back off to store it, net zero. The `default` branch below
			// assumes a trailing statement leaves exactly one value that
			// still needs popping, which holds for other statement kinds but
			// not this one; applying its OpPop here popped one value too
			// many. For a *local* catch parameter that extra pop dropped the
			// VM's stack pointer one slot INTO the function's reserved
			// locals region, corrupting an unrelated local variable's slot
			// (observed live: a later `for x in <that corrupted local>`
			// loop hung indefinitely). keepValue=true (OpDup) instead
			// leaves exactly the assigned value on the stack, matching how a
			// trailing VarStatement is already treated as the value of an
			// if-branch or function body (see compileVarStatement's keepValue
			// comment) -- so no extra OpPop is emitted for this case.
			if err := c.compileVarStatement(s, true); err != nil {
				return err
			}
		default:
			if err := c.Compile(last); err != nil {
				return err
			}
			c.emit(OpPop)
		}
	}

	endPos := c.emit(OpJump, 9999)

	afterCatch := len(c.currentInstructions())
	c.patchJump(skipCatchPos, afterCatch)
	if skipFixPos != 0 {
		c.patchJump(skipFixPos, afterCatch)
	}
	for _, pos := range catchJumps {
		c.patchJump(pos, catchBind)
	}

	c.patchJump(endPos, len(c.currentInstructions()))

	return nil
}

// compileTryBlockStatement compiles one statement of a try block, leaving its
// result on the stack so the following error check can inspect it.
func (c *Compiler) compileTryBlockStatement(stmt ast.Statement) error {
	switch s := stmt.(type) {
	case *ast.ExpressionStatement:
		return c.Compile(s.Expression)
	case *ast.VarStatement:
		return c.compileVarStatement(s, true)
	default:
		if err := c.Compile(stmt); err != nil {
			return err
		}
		c.emit(OpPop)
		return nil
	}
}

func blockSourceFromStatements(stmts []ast.Statement) string {
	if len(stmts) == 0 {
		return "(empty)"
	}
	if len(stmts) == 1 {
		if es, ok := stmts[0].(*ast.ExpressionStatement); ok {
			s := es.Expression.String()
			if len(s) > 2 && s[0] == '(' && s[len(s)-1] == ')' {
				s = s[1 : len(s)-1]
			}
			return s
		}
	}
	var parts []string
	for _, stmt := range stmts {
		parts = append(parts, fmt.Sprintf("%s", stmt))
	}
	return strings.Join(parts, "; ")
}

func (c *Compiler) compilePipeline(pe *ast.PipelineExpression) error {
	callOp := OpCall
	if pe.Parallel {
		callOp = OpSpawn
	}

	switch right := pe.Right.(type) {
	case *ast.Identifier:
		sym, ok := c.symbolTable.Resolve(right.Value)
		if !ok {
			return fmt.Errorf("undefined function: %s", right.Value)
		}
		c.loadSymbol(sym)
		if err := c.Compile(pe.Left); err != nil {
			return err
		}
		c.emit(callOp, 1)

	case *ast.CallExpression:
		if err := c.Compile(right.Function); err != nil {
			return err
		}
		if err := c.Compile(pe.Left); err != nil {
			return err
		}
		for _, arg := range right.Arguments {
			if err := c.Compile(arg); err != nil {
				return err
			}
		}
		c.emit(callOp, len(right.Arguments)+1)

	default:
		if err := c.Compile(pe.Right); err != nil {
			return err
		}
		if err := c.Compile(pe.Left); err != nil {
			return err
		}
		c.emit(callOp, 1)
	}

	return nil
}

func (c *Compiler) loadSymbol(s Symbol) {
	switch s.Scope {
	case GlobalScope:
		c.emit(OpGetGlobal, s.Index)
	case LocalScope:
		c.emit(OpGetLocal, s.Index)
	case BuiltinScope:
		c.emit(OpGetBuiltin, s.Index)
	case FreeScope:
		c.emit(OpGetFree, s.Index)
	}
}

func (c *Compiler) enterLoop(continueTarget int) {
	c.loopStack = append(c.loopStack, LoopContext{
		continueTarget: continueTarget,
		breakPatches:   []int{},
	})
}

// enterLoopPending registers a loop whose continue target (the update clause)
// is only known after the body compiles. Continues are emitted as patchable
// forward jumps and resolved with patchContinues.
func (c *Compiler) enterLoopPending() {
	c.loopStack = append(c.loopStack, LoopContext{
		continueTarget:  -1,
		continuePatches: []int{},
		breakPatches:    []int{},
	})
}

func (c *Compiler) leaveLoop() {
	c.loopStack = c.loopStack[:len(c.loopStack)-1]
}

func (c *Compiler) addBreak() {
	if len(c.loopStack) == 0 {
		return
	}
	loop := &c.loopStack[len(c.loopStack)-1]
	loop.breakPatches = append(loop.breakPatches, c.emit(OpJump, 9999))
}

func (c *Compiler) patchBreaks(afterLoop int) {
	if len(c.loopStack) == 0 {
		return
	}
	loop := &c.loopStack[len(c.loopStack)-1]
	for _, pos := range loop.breakPatches {
		c.patchJump(pos, afterLoop)
	}
	loop.breakPatches = nil
}

func (c *Compiler) emitContinue() {
	if len(c.loopStack) == 0 {
		return
	}
	loop := &c.loopStack[len(c.loopStack)-1]
	if loop.continueTarget < 0 {
		loop.continuePatches = append(loop.continuePatches, c.emit(OpJump, 9999))
		return
	}
	c.emit(OpJumpBackward, loop.continueTarget)
}

func (c *Compiler) patchContinues(target int) {
	if len(c.loopStack) == 0 {
		return
	}
	loop := &c.loopStack[len(c.loopStack)-1]
	for _, pos := range loop.continuePatches {
		c.patchJump(pos, target)
	}
	loop.continuePatches = nil
}

func (c *Compiler) compileForIn(fe *ast.ForExpression) error {
	// Bug fix: __list__/__idx__ used to be fixed names, so a NESTED for-loop
	// (compiled in the same symbol-table scope as its enclosing loop -- a
	// for-loop body doesn't open its own enclosed scope) would Define() the
	// exact same symbols as the outer loop, per Define()'s "already exists
	// in this scope -> return the existing slot" rule. The inner loop's own
	// init/increment code then overwrote the outer loop's __list__/__idx__
	// values while the outer loop was still mid-iteration; once the inner
	// loop finished and control returned to the outer loop's own condition
	// check, it read back the INNER loop's post-loop state (its list, its
	// final index) instead of its own, so the condition falsely evaluated
	// false and the outer loop exited after just its first iteration.
	// Reproduced live: `for o in outer { for i in inner { ... } }` only ever
	// ran the outer loop's first iteration, no matter how many elements
	// `outer` had. A unique suffix per compiled for-loop gives every loop
	// (nested or not) its own slots.
	c.forInCounter++
	suffix := strconv.Itoa(c.forInCounter)
	iterSym := c.symbolTable.Define(fe.Iterator.Value)
	listSym := c.symbolTable.Define("__list__" + suffix)
	idxSym := c.symbolTable.Define("__idx__" + suffix)

	if err := c.Compile(fe.Iterable); err != nil {
		return err
	}
	c.emitSet(listSym)

	c.emit(OpConstant, c.addInteger(0))
	c.emitSet(idxSym)

	loopStart := len(c.currentInstructions())

	// idx < len(list): push idx, then builtin len, then list
	c.emitGet(idxSym)
	c.emit(OpGetBuiltin, c.resolveBuiltin("len").Index)
	c.emitGet(listSym)
	c.emit(OpCall, 1)
	c.emit(OpLess)
	jumpFalsePos := c.emit(OpJumpNotTruthy, 9999)

	// list[idx]: push builtin at, then args
	c.emit(OpGetBuiltin, c.resolveBuiltin("at").Index)
	c.emitGet(listSym)
	c.emitGet(idxSym)
	c.emit(OpCall, 2)
	c.emitSet(iterSym)

	c.enterLoop(loopStart)
	if err := c.compileStatements(fe.Body.Statements, true); err != nil {
		return err
	}
	c.leaveLoop()

	c.emitGet(idxSym)
	c.emit(OpConstant, c.addInteger(1))
	c.emit(OpAdd)
	c.emitSet(idxSym)

	c.emit(OpJumpBackward, loopStart)

	afterLoop := len(c.currentInstructions())
	c.patchJump(jumpFalsePos, afterLoop)
	c.patchBreaks(afterLoop)

	c.emit(OpNil)

	return nil
}

func (c *Compiler) compileCStyleFor(fe *ast.ForExpression) error {
	// Init clause: for i: 0; cond; update
	if fe.Init != nil {
		if err := c.Compile(fe.Init); err != nil {
			return err
		}
	}

	conditionPos := len(c.currentInstructions())
	if fe.Condition != nil {
		if err := c.Compile(fe.Condition); err != nil {
			return err
		}
	} else {
		c.emit(OpConstant, c.addInteger(1)) // no condition → infinite loop
	}
	jumpFalsePos := c.emit(OpJumpNotTruthy, 9999)

	c.enterLoopPending()
	if err := c.compileStatements(fe.Body.Statements, true); err != nil {
		return err
	}

	updatePos := len(c.currentInstructions())
	if fe.Update != nil {
		if err := c.Compile(fe.Update); err != nil {
			return err
		}
	}
	c.emit(OpJumpBackward, conditionPos)

	afterLoop := len(c.currentInstructions())
	c.patchJump(jumpFalsePos, afterLoop)
	c.patchContinues(updatePos)
	c.patchBreaks(afterLoop)
	c.leaveLoop()

	c.emit(OpNil)

	return nil
}

func (c *Compiler) emitGet(s Symbol) {
	if s.Scope == GlobalScope {
		c.emit(OpGetGlobal, s.Index)
	} else {
		c.emit(OpGetLocal, s.Index)
	}
}

func (c *Compiler) emitSet(s Symbol) {
	if s.Scope == GlobalScope {
		c.emit(OpSetGlobal, s.Index)
	} else {
		c.emit(OpSetLocal, s.Index)
	}
}

func (c *Compiler) resolveBuiltin(name string) Symbol {
	for i, bi := range object.Builtins {
		if bi.Name == name {
			return Symbol{Name: name, Scope: BuiltinScope, Index: i}
		}
	}
	return Symbol{}
}

func (c *Compiler) patchJump(pos int, target int) {
	ins := c.currentScope().instructions
	ins[pos+1] = byte(target >> 8)
	ins[pos+2] = byte(target)
}

func (c *Compiler) lastIsReturn() bool {
	ins := c.currentScope().instructions
	if len(ins) < 3 {
		return false
	}
	last := Opcode(ins[len(ins)-3])
	return last == OpReturn || last == OpReturnValue
}

func (c *Compiler) compileDefer(de *ast.DeferStatement) error {
	prevLen := len(c.currentScope().instructions)
	c.currentScope().instructions = c.currentScope().instructions[:prevLen]
	c.currentScope().lines = c.currentScope().lines[:prevLen]

	if err := c.Compile(de.Expression); err != nil {
		return err
	}

	deferCode := make(Instructions, len(c.currentScope().instructions)-prevLen)
	copy(deferCode, c.currentScope().instructions[prevLen:])
	deferLines := make([]int, len(c.currentScope().lines)-prevLen)
	copy(deferLines, c.currentScope().lines[prevLen:])
	c.currentScope().instructions = c.currentScope().instructions[:prevLen]
	c.currentScope().lines = c.currentScope().lines[:prevLen]

	c.currentScope().deferred = append(c.currentScope().deferred, deferCode)
	c.currentScope().deferredLines = append(c.currentScope().deferredLines, deferLines)
	return nil
}

func (c *Compiler) compileImport(is *ast.ImportStatement) error {
	cacheKey := is.Path

	// Use cached parse result or parse fresh
	program, ok := c.importCache[cacheKey]
	if !ok {
		var resolvedPath string
		var err error
		resolvedPath, program, err = object.ResolveAndParse(is.Path, c.sourceFile)
		if err != nil {
			return fmt.Errorf("import %s: %w", is.Path, err)
		}
		// Use resolved path as cache key (may differ from is.Path)
		cacheKey = resolvedPath
		c.importCache[cacheKey] = program
	}

	// Circular import detection: if this module is already being compiled
	// further up the import chain, this is a cycle (a.pipe -> b.pipe -> a.pipe).
	for _, inProgress := range c.importStack {
		if inProgress == cacheKey {
			chain := append(append([]string{}, c.importStack...), cacheKey)
			return fmt.Errorf("E009: circular import: %s", strings.Join(chain, " -> "))
		}
	}

	aliased := is.Alias != ""

	// Unaliased flat imports: skip recompilation when the module was already
	// imported this way and just re-bind its export aliases into the current
	// scope (the tree-walker re-injects exports from the shared module
	// instance). Aliased imports each bind their own namespace, so they are
	// compiled again.
	if !aliased {
		if binds, ok := c.importedExports[cacheKey]; ok {
			c.bindImportAliases(binds)
			return nil
		}
	}

	c.importStack = append(c.importStack, cacheKey)
	defer func() { c.importStack = c.importStack[:len(c.importStack)-1] }()

	// Compile the module in an isolated symbol scope: definitions occupy real
	// global slots but stay invisible to the importer; afterwards only the
	// exported names (all names when the module exports nothing) are bound as
	// aliases. This mirrors the tree-walker, which evaluates every module in
	// a fresh environment.
	modTab := NewModuleSymbolTable(c.symbolTable)
	savedTable := c.symbolTable
	c.symbolTable = modTab

	// Pre-define the module's top-level names so intra-module forward
	// references resolve, exactly like the main program's pre-pass.
	c.defineTopLevelSymbols(program.Statements)

	var names []string
	hasExports := false
	exports := make(map[string]bool)
	record := func(name string) {
		for _, n := range names {
			if n == name {
				return
			}
		}
		names = append(names, name)
	}

	for _, stmt := range program.Statements {
		switch s := stmt.(type) {
		case *ast.FnStatement:
			if err := c.Compile(s); err != nil {
				return fmt.Errorf("import %s: %w", is.Path, err)
			}
			record(s.Name.Value)
		case *ast.VarStatement:
			if err := c.Compile(s); err != nil {
				return fmt.Errorf("import %s: %w", is.Path, err)
			}
			record(s.Name.Value)
		case *ast.EnumStatement:
			if err := c.Compile(s); err != nil {
				return fmt.Errorf("import %s: %w", is.Path, err)
			}
			for _, name := range s.Values {
				record(name)
			}
		case *ast.StructStatement:
			if err := c.Compile(s); err != nil {
				return fmt.Errorf("import %s: %w", is.Path, err)
			}
			record(s.Name)
		case *ast.ExportStatement:
			if s.Fn != nil {
				if err := c.Compile(s.Fn); err != nil {
					return fmt.Errorf("import %s: %w", is.Path, err)
				}
				record(s.FnName)
				exports[s.FnName] = true
			}
			if s.Var != nil {
				if err := c.Compile(s.Var); err != nil {
					return fmt.Errorf("import %s: %w", is.Path, err)
				}
				record(s.VarName)
				exports[s.VarName] = true
			}
			if s.Enum != nil {
				if err := c.Compile(s.Enum); err != nil {
					return fmt.Errorf("import %s: %w", is.Path, err)
				}
				for _, val := range s.Enum.Values {
					record(val)
					exports[val] = true
				}
			}
			hasExports = true
		case *ast.ImportStatement:
			if err := c.compileImport(s); err != nil {
				return fmt.Errorf("import %s: %w", is.Path, err)
			}
		case *ast.ExpressionStatement:
			// skip standalone expressions in imports
		}
	}

	c.symbolTable = savedTable

	// Collect the visibility selection from the module scope.
	binds := make([]Symbol, 0, len(names))
	for _, n := range names {
		if hasExports && !exports[n] {
			continue
		}
		if sym, ok := modTab.store[n]; ok {
			binds = append(binds, sym)
		}
	}
	sort.Slice(binds, func(i, j int) bool { return binds[i].Name < binds[j].Name })

	// Aliased imports bind a namespace map of the module's exports, matching
	// the tree-walker's `import "m" as ns` -> `ns.name` access.
	if aliased {
		c.emitNamespaceMap(is.Alias, binds)
	} else {
		c.bindImportAliases(binds)
		c.importedExports[cacheKey] = binds
	}
	return nil
}

// bindImportAliases injects an already-compiled module's export symbols into
// the current scope as FromImport aliases.
func (c *Compiler) bindImportAliases(binds []Symbol) {
	for _, sym := range binds {
		c.symbolTable.DefineAlias(sym.Name, sym)
	}
}

// emitNamespaceMap binds `alias` to a map of the just-compiled module's
// exported top-level names, mirroring the tree-walker's namespace object.
func (c *Compiler) emitNamespaceMap(alias string, binds []Symbol) {
	for _, sym := range binds {
		c.loadSymbol(sym)
	}
	if len(binds) == 0 {
		c.emit(OpNil)
	} else {
		c.emit(OpMap, len(binds))
		for _, sym := range binds {
			ki := c.addString(sym.Name)
			c.emitUint16(uint16(ki))
		}
	}

	sym := c.symbolTable.Define(alias)
	if sym.Scope == GlobalScope {
		c.emit(OpSetGlobal, sym.Index)
	} else {
		c.emit(OpSetLocal, sym.Index)
	}
}

func (c *Compiler) resolveImport(path string) (string, *ast.Program, error) {
	return object.ResolveAndParse(path, c.sourceFile)
}

func (c *Compiler) defineTopLevelSymbols(stmts []ast.Statement) {
	for _, stmt := range stmts {
		switch s := stmt.(type) {
		case *ast.FnStatement:
			c.symbolTable.Define(s.Name.Value)
		case *ast.VarStatement:
			c.symbolTable.Define(s.Name.Value)
		case *ast.EnumStatement:
			for _, name := range s.Values {
				c.symbolTable.Define(name)
			}
		case *ast.StructStatement:
			c.symbolTable.Define(s.Name)
		case *ast.ExportStatement:
			if s.Fn != nil {
				c.symbolTable.Define(s.Fn.Name.Value)
			}
			if s.Var != nil {
				c.symbolTable.Define(s.Var.Name.Value)
			}
			if s.Enum != nil {
				for _, name := range s.Enum.Values {
					c.symbolTable.Define(name)
				}
			}
		case *ast.ImportStatement:
			// Module internals stay isolated in their own scope; exported
			// names become visible exactly when the import statement is
			// compiled, matching the tree-walker's sequential evaluation.
			continue
		}
	}
}

func (c *Compiler) enterScope() {
	scope := CompilationScope{instructions: Instructions{}, deferred: nil}
	c.scopes = append(c.scopes, scope)
	c.scopeIndex++
	c.symbolTable = NewEnclosedSymbolTable(c.symbolTable)
}

func (c *Compiler) leaveScope() CompiledScope {
	scope := c.scopes[c.scopeIndex]

	// Emit all deferred expressions in LIFO order
	for i := len(scope.deferred) - 1; i >= 0; i-- {
		scope.instructions = append(scope.instructions, scope.deferred[i]...)
		scope.lines = append(scope.lines, scope.deferredLines[i]...)
	}

	nl := c.symbolTable.numDefinitions
	free := c.symbolTable.FreeSymbols
	c.scopes = c.scopes[:c.scopeIndex]
	c.scopeIndex--
	c.symbolTable = c.symbolTable.Outer
	return CompiledScope{Instructions: scope.instructions, Lines: scope.lines, NumLocals: nl, FreeSymbols: free}
}

// Pretty-print instructions for debugging
func (ins Instructions) String() string {
	var out string
	i := 0
	for i < len(ins) {
		op := Opcode(ins[i])
		switch op {
		case OpClosure:
			if i+5 > len(ins) {
				out += fmt.Sprintf("%04d %-14s (truncated)\n", i, op)
				break
			}
			out += fmt.Sprintf("%04d %-14s %d %d\n", i, op, ReadUint16(ins, i+1), ReadUint16(ins, i+3))
			i += 5
		case OpConstant, OpGetGlobal, OpSetGlobal, OpGetLocal, OpSetLocal,
			OpGetBuiltin, OpDot, OpGetFree,
			OpTestAbortIfError, OpTestResult, OpSelect:
			if i+3 > len(ins) {
				out += fmt.Sprintf("%04d %-14s (truncated)\n", i, op)
				break
			}
			out += fmt.Sprintf("%04d %-14s %d\n", i, op, ReadUint16(ins, i+1))
			i += 3
		case OpCall, OpList:
			if i+3 > len(ins) {
				out += fmt.Sprintf("%04d %-14s (truncated)\n", i, op)
				break
			}
			out += fmt.Sprintf("%04d %-14s %d\n", i, op, ReadUint16(ins, i+1))
			i += 3
		case OpMap:
			if i+3 > len(ins) {
				out += fmt.Sprintf("%04d %-14s (truncated)\n", i, op)
				break
			}
			numPairs := int(ReadUint16(ins, i+1))
			out += fmt.Sprintf("%04d %-14s %d pairs\n", i, op, numPairs)
			i += 3
			for j := 0; j < numPairs && i+2 <= len(ins); j++ {
				ki := ReadUint16(ins, i)
				out += fmt.Sprintf("%04d   key=%d\n", i, ki)
				i += 2
			}
		case OpJump, OpJumpNotTruthy, OpJumpBackward:
			if i+3 > len(ins) {
				out += fmt.Sprintf("%04d %-14s (truncated)\n", i, op)
				break
			}
			out += fmt.Sprintf("%04d %-14s %d\n", i, op, ReadUint16(ins, i+1))
			i += 3
		default:
			out += fmt.Sprintf("%04d %s\n", i, op)
			i++
		}
	}
	return out
}

func ParseFloat(s string) float64 {
	f, _ := strconv.ParseFloat(s, 64)
	return f
}

var zeroArityBuiltins = map[string]bool{
	"now":               true,
	"time_ms":           true,
	"random":            true,
	"secure_random_int": true,
	"try_ai_log":        true,
	"args":              true,
	"read_stdin":        true,
	"ai_cost":           true,
	"ai_tokens":         true,
	"ai_cache_hits":     true,
	"ai_cache_misses":   true,
	"audit_log":         true,
	"budget_spent":      true,
	"mcp_serve_stdio":   true,
	"mcp_tools":         true,
	"mcp_resources":     true,
	"mcp_prompts":       true,
	"mutex":             true,
}

func isZeroArityBuiltin(name string) bool {
	return zeroArityBuiltins[name]
}
